# First steps with data analysis in Python

A workshop at [Aspects of Neuroscience](http://neuroaspects.org/) 2016, by [Piotr Migdał](http://p.migdal.pl/).

# 2. More of Python

## Packages

Most of functionalities are in packages. Some are built-in, other require installation.

Anaconda distribution starts with common scientific packages.

In [1]:
import math

In [2]:
math.sqrt(2)

1.4142135623730951

In [5]:
math.atan?

In [6]:
import numpy as np

In [7]:
np.sqrt(2)

1.4142135623730951

In [10]:
np.sqrt?

In [8]:
v = np.array([1, 2])
v

array([1, 2])

In [9]:
M = np.array([[1, -4], [-3, 8]])
M

array([[ 1, -4],
       [-3,  8]])

In [14]:
# Python only 3.5+
M @ v

array([-7, 13])

In [12]:
M.dot(v)

array([-7, 13])

## Filesystem

Reading and writing files is a way to interact with data.

In [15]:
import glob

In [20]:
glob.glob("*")

['0_intro.ipynb',
 '1_basic_programming.ipynb',
 '2_more_of_python.ipynb',
 '3_data_analysis.ipynb',
 'README.md',
 'bike_sharing_day.csv']

In [17]:
glob.glob("*.md")

['README.md']

In [18]:
file = open("README.md")
text = file.read()
file.close()
print(text)

# First steps with data analysis in Python

[First steps with data analysis in Python](First steps with data analysis in Python) - a 3h hands-on workshop at [Aspects of Neuroscience 2016](http://neuroaspects.org/), 25-27th November 2016 (Warsaw, Poland), by [Piotr Migdał, PhD](http://p.migdal.pl/).

## Abstract

Do you want to learn how to write scripts, and use programming to solve practical data analysis problems? Python is the way to go! It starts in a simple way, but is one of the best environments for data science (including machine learning and artificial neural networks).

You will learn how to load data, process it and make plots.It is a basic introduction, starting from basic structures (like dictionaries and lists) and control flow (if, else, loops). If you are clicking your way to get results, or not yet comfortable it any programming language (but would love to change that!), it is for you!

We will be using [Jupyter Notebook](http://jupyter.org/) - an environment, which ma

In [22]:
# or to make sure it will get closed
with open("README.md") as file:
    text = file.read()
    print(text[:300])

# First steps with data analysis in Python

[First steps with data analysis in Python](First steps with data analysis in Python) - a 3h hands-on workshop at [Aspects of Neuroscience 2016](http://neuroaspects.org/), 25-27th November 2016 (Warsaw, Poland), by [Piotr Migdał, PhD](http://p.migdal.pl/).



In [23]:
with open("README_short.md", 'w') as file_to_write:
    file_to_write.write(text[:300])

## Internet

Getting data from anywhere!

In [24]:
import requests

In [25]:
r = requests.get("http://p.migdal.pl/")

In [26]:
r.status_code

200

In [29]:
r.text[:1000]

'<!DOCTYPE html>\n<html>\n\n  <head>\n  <meta charset="utf-8">\n  <meta http-equiv="X-UA-Compatible" content="IE=edge">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n\n  <title>Piotr Migdał - blog</title>\n  <meta name="description" content="Piotr Migdał - a data science freelancer, with PhD in quantum physics; based in Warsaw, Poland. Active in gifted education, developing a Quantum Game.\n">\n\n  <link rel="stylesheet" href="/css/main.css">\n  <link rel="canonical" href="http://p.migdal.pl/">\n  <link rel="alternate" type="application/rss+xml" title="Piotr Migdał - blog" href="http://p.migdal.pl/feed.xml">\n  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">\n\n  <meta content="Piotr Migdał - blog" property="og:site_name">\n  \n    <meta content="Piotr Migdał - blog" property="og:title">\n  \n  \n    <meta content="website" property="og:type">\n  \n  \n    <meta content="Piotr Migdał - a data science 

In [40]:
# https://developers.google.com/maps/documentation/geocoding/start
r = requests.get("https://maps.googleapis.com/maps/api/geocode/json",
                 params={"address": "Mount Everest"})

In [41]:
data = r.json()

In [42]:
data.keys()

dict_keys(['results', 'status'])

In [43]:
data["results"][0]["geometry"]["location"]

{'lat': 27.98785, 'lng': 86.9250261}

## Installing packages

On Linux / OS X you can do it from within Jupyter Notebook. On Windows - open

Typically things are installed with `pip install`, from the [PyPI repository](https://pypi.org/).

In [44]:
!pip install tqdm

In [45]:
from tqdm import tqdm
from time import sleep

In [46]:
sleep(2)

In [48]:
for i in tqdm(range(10)):
    sleep(0.5)

100%|██████████| 10/10 [00:05<00:00,  1.98it/s]
